# Generated by Django 2.0.5 on 2018-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('running', 'running'), ('active', 'active'), ('complete', 'complete'), ('terminated', 'terminated'), ('suspended', 'suspended')], default='initiated', max_length=10)),
                ('old_status', models.CharField(blank=True, choices=[('initiated', 'initiated'), ('running', 'running'), ('active', 'active'), ('complete', 'complete'), ('terminated', 'terminated'), ('suspended', 'suspended')], max_length=10, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('blocked', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('blocked', 'blocked'), ('inactive', 'inactive'), ('active', 'active'), ('suspended', 'suspended'), ('fallout', 'fallout'), ('complete', 'complete')], default='inactive', max_length=10)),
            ],
            options={
                'permissions': (('can_change_priority', 'Can change priority'),),
            },
        ),
    ]
