# Generated by Django 2.0.5 on 2018-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, editable=False, null=True, verbose_name='history')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Simulation object',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='catagory')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Icon',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='category')),
                ('file', models.ImageField(upload_to='images', verbose_name='file')),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='ImageButton',
            fields=[
                ('action', models.SlugField(primary_key=True, serialize=False, verbose_name='action')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptools.Icon', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Image Button',
            },
        ),
    ]
