# Generated by Django 2.0.5 on 2018-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('graphics2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processimage',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Process'),
        ),
        migrations.AddField(
            model_name='activityposition',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Activity'),
        ),
        migrations.AddField(
            model_name='activityposition',
            name='diagram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics2.ProcessImage'),
        ),
    ]
