XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
XXXXXX
XXXXXXXBBBBB BBBBBXXXXXX XXXXXX XXXXXXXBBBBBBBBXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXX
XXXXBBBBB BBBBBBBBBBXXXXXX XXXXXX XXXXXXXBBBBBBBBXXXXX

 XXXX XXXXXXXXXX
  XXX XXXXXXXXX
   BBBBB BBBBBBBBBBBBBBBBB
   XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
   XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXX
 XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXX

XXXX XXXXXXXXXXX
BBBBB BBBBBBB
XXXXXXXXX XXXXXXXXXX
XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXXXXX XXXXXXXXXX
XXXXXXXXX XXXXXXXXXX
XXX
XX XXXXXXXXXXX XXXXX XXXXX XXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXX XX XXXXXX XXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXX XX XXXXXX XX XXXX XXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXX XXX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXX XXXXXX XXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXX XX XXXXXX XXXXXXX XXXX XXXXX XXXXXX XXXXX XXX XXXX XXXXXXXXX XXXX XXXXX XXX XXXXXX XX XXXX XXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXX XXXXXX XXXX XXXXXXXXX XXX XXXXXXX XXXXXXXX XX XXXXXX XXXXX XXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXX XXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXX XXXXX
XXXX
XXX
XXXX XXXXXXX XXXXX XX XXXXXX XXXXXXXXX XXX XXXXXXX XXXXXXXXXX XX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXX XXXXXXXX XXXXX XXXXX XX XXX XXXXXXX XXXX XXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXX XXXX XXXXXX XXX XXXXXX XXXX XXXXXXX XXXXX XX XXXXXXX XXXXX XXXXXXXXXX XXXXXX XX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXX XXXXX XXXXX XXX XXXXX XXX XXXXXXXXXX XXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXX XX XXXX XXXXX XXXXXX XXX XXXXXXXX XXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX X XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
XXXX
XXX
XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXX XXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXX XX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXX X XXXX XXX XXXXX XXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXX XXXXXXXXX XXXXX XXXXXXX XXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXX XXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX XXXXX XXXXXX XXXXX XXX XXXXX XXX XXXXXXXX XXXXXXXX XXXX XXXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XXX XXXXXXXXX XX XXXXX XXX XXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XXXX XXXXXXX XX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXX
XXXX
XXX
XXXXXX XXXXXXXX XXX XXXXX XXXXXXXX XXXXXX XXX XXXXX XXXXXXX XXXX XX XXXXXXXXX XXXX XXXXXX XX XXXXXX XXXXXXXXXX XXXXXXXXX XXXXX XX XXXXXX XXXXXXXXXXXX XXX XXXXX XXXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXX XXXXX XX XXXX XXXXX XXXXXXX XXXXX XX XXXXXX XXXXX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXX XX XXXXX XXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXX XXXXXX XXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXX XXXXXX XX XXXXXXX XXX XXXX XX XXXXX XX XXXXXX XXXXXX XX XXXXXX XX XXXX XXXXXXXXXXX XXXXXXXXX
XXXX
BBBBBBBB
XXXXXX
	
XXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXBBBBB BBBBBBBBBBBBBBBXXXXXX
    
    BBBBB BBBBB
	XXXX XXXXXXXXXXXX
			XXXXXXXX XXXXXX	
			XXXXXXXXX XXXX XXXXXXXX
	XXXXXX
	BBBBBBBB

	XXXX XXXXXXXXXXXX
		XXXXXXXXXXXXXXXXX
		BBBB BBBBBBBBBBBBBBBBBBB
	   XXXX XXXXXXXXXXXXXXXXX XXXXXXXX
	   XXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	   XXXXXX
	XXXXXX
			
	XXXX XXXXXXXXXXXX
				XXXXXXXXX XXXXXX
				XXXX
				XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
				XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
				XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
	XXXXXX
		
    XXXX XXXXXXXXXXXX
	   XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
	XXXXXX
	
    XXXX XXXXXXXXXXXXXXXX
	XXXXXXXXXXXX
	XXXXXX
XXXXXX
XXXXXX
XXXXXXX
XXXXXXX