# Generated by Django 2.0.5 on 2018-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_attr', models.CharField(default='parent', max_length=50)),
                ('children_attr', models.CharField(default='children', max_length=50)),
                ('position_method', models.CharField(default='position', max_length=50)),
                ('zorder_method', models.CharField(default='zorder', max_length=50)),
                ('moveable_method', models.CharField(default='is_moveable', max_length=50)),
                ('content_type', models.ManyToManyField(to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='graphics.MetaGraph')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Graph')),
            ],
        ),
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(default=0)),
                ('y', models.PositiveSmallIntegerField(default=0)),
                ('w', models.PositiveSmallIntegerField(default=0)),
                ('h', models.PositiveSmallIntegerField(default=0)),
                ('need_update', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('z', models.PositiveSmallIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Graph')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graphics.Image')),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bg_graphes', to='graphics.Visual'),
        ),
        migrations.AddField(
            model_name='graph',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='graphics.Graph'),
        ),
    ]
