# Generated by Django 2.0.5 on 2018-05-17 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='vacations, rtt, ..', max_length=50)),
                ('days', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(upload_to='leave')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Leave Attachment',
                'verbose_name_plural': 'Leave Attachment',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('day_start', models.DateField()),
                ('day_end', models.DateField()),
                ('type', models.CharField(choices=[('Vacation', 'Vacation'), ('Birth or marriage of child', 'Birth or marriage of child'), ('Change of residence', 'Change of residence'), ('Death of a child', 'Death of a child'), ('Death of a relative in the ascending line', 'Death of a relative in the ascending line'), ('Death of parent-in-law, brother or sister', 'Death of parent-in-law, brother or sister'), ('Death of spouse', 'Death of spouse'), ('Marriage', 'Marriage'), ('Maternity', 'Maternity'), ('Serious illness of a child', 'Serious illness of a child'), ('Serious illness of a relative in the asc line', 'Serious illness of a relative in the asc line'), ('Serious illness of a parent-in-law', 'Serious illness of a parent-in-law'), ('Serious illness of spouse', 'Serious illness of spouse')], default='Vacation', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reason_denial', models.TextField(blank=True, null=True, verbose_name='reason of denial')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('secretary', 'Secretary'), ('supervisor', 'Supervisor')], help_text='secretary, supervisor, ...', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_set', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leaveattachment',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.LeaveRequest', verbose_name='Leave Request'),
        ),
    ]
